### ISSUE TITLE
No work

### ISSUE THREAD

**Issue by Suburbanno** [Psykotik/Championizer#2]
![videotogif_2017 01 07_21 20 58 1](https://cloud.githubusercontent.com/assets/13632826/21746344/97a3316c-d528-11e6-9760-9e4cccf5cc1a.gif)

**Comment by Suburbanno** [comment]
;-;

**Comment by Suburbanno** [comment]
J2 5.1.1

**Comment by Psykotik** [comment]
Thanks for your review. I've patched this bug. You can download the new app right from the release page !
